---
- name: configuring nfs-clinet 
  hosts: nfs_clients
  become: true
  tasks:
          - name: ensure nfs-utils is installed 
            yum:
                    name: nfs-utils
                    state: present

          - name: creating nfs mounting directory 
            file:
                    name: /nfs_receive
                    state: directory

          - name: For permanent mounting 
            mount:
                    path: /nfs_receive
                    src: server.example.com:/nfs_share 
                    state: mounted 
                    fstype: nfs
