---
- name: configuring nfs server
  hosts: nfs-server
  become: true
  tasks:
          - name: ensure nfs-utils is installed 
            yum:
                    name: nfs-utils
                    state: present

          - name: creating sharing directory
            file:
                    path: /nfs_share
                    state: directory
                    owner: root
                    group: root

          - name: creating configuration files
            file:
                    path: /etc/exports.d/server.exports
                    state: touch

          - name: copying contents to the configuratin files
            copy:
                    src: templates/server.exports.j2
                    dest: /etc/exports.d/server.exports

          - name: starting nfs-service
            service:
                    name: nfs-server
                    state: started
                    enabled: true

          - name: enabling services from firewall
            firewalld:
                    service: "{{ item }}"
                    state: enabled
                    immediate: yes
                    permanent: true
            loop:
              - nfs
              - rpc-bind
              - mountd
               
