---
- name: ensure that the secndary dns server is active and running 
  hosts: centos
  become: true
  tasks:
           - name: ensure bind packages is present on secondary server 
             yum:
                    name: bind
                    state: present

           - name: ensure named.conf file is correct
             copy:
               src: files/named.conf
               dest: /etc/named.conf
               owner: root
               group: named
               mode: '0640'
               setype: named_conf_t

           - name: ensure zone configuration file are present
             copy:
               src: files/named.secondary.backend.conf
               dest: /etc/named.backedn.conf
               owner: root
               group: named
               mode: '0640'
               setype: named_conf_t

           - name: ensure named service is restarted
             service:
               name: named
               state: restarted
               enabled: true

           - name: ensure that the firewall allows dns service
             firewalld:
               service: dns
               immediate: true
               state: enabled
               permanent: true

          
