---
- name: Performing DHCP Tasks!
  hosts: server
  become: true
  vars:
          network_connections:
                  - name: dhcp_con
                    interface_name: ens224
                    type: ethernet
                    ip:
                            dhcp4: false
                            auto6: false
                            address:
                                    - "192.168.1.10/24"
                                    - "fde2:6494:1e09:2::a/64"

  roles:
          - rhel-system-roles.network 

  tasks:
          - name: ensure static IP on server
            command: /usr/bin/nmcli con up dhcp_con
          
          - name: restarting NetworkManager service
            service:
                    name: NetworkManager
                    state: restarted

          - name:  ensure dhcp-server packages is present!
            yum:
                    name: dhcp-server
                    state: present

          - name: copying configuration files 
            template:
                    src: templates/dhcpd.conf.j2
                    dest: /etc/dhcp/dhcpd.conf
                    owner: root
                    group: root
                    mode: '0644'

          - name: copying ipv6 configuration files
            template:
                    src: templates/dchpd6.conf.j2
                    dest: /etc/dhcp/dhcpd6.conf
                    owner: root
                    group: root
                    mode: '0644'
          
          - name: ensure dhcp service is started and enabled
            service:
                    name: "{{ item }}"
                    state: started
                    enabled: true
            loop:
                    - dhcpd
                    - dhcpd6

          - name: ensure dhcp service is available from firewall 
            firewalld:
                    service: "{{ item }}"
                    immediate: true
                    permanent: true
                    state: enabled
  
            loop:
                    - dhcp
                    - dhcv6
